local RewardTypeMetadata = {
	LuckMultiplier = {
		icon = "98748609480531",
		labelFormat = "+%d%%",
		descriptionFormat = "Permanently increases your luck by %d%%",
	},
	MoneyMultiplier = {
		icon = "88625177615779",
		labelFormat = "+%d%%",
		descriptionFormat = "Permanently increases your money gain by %d%%",
	},
	BaseLuck = {
		icon = "121193370101444",
		labelFormat = "+%d",
		descriptionFormat = "Permanently adds +%d to your base luck",
	},
}

return RewardTypeMetadata